FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server.py .
COPY generated ./generated

# Add the generated directory to PYTHONPATH
ENV PYTHONPATH=/app/generated:$PYTHONPATH

EXPOSE 50051

CMD ["python", "-u", "server.py"]
