FROM golang:latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY client.go .
COPY generated ./generated

RUN go build -o client .

ENV SERVER_ADDRESS=host.docker.internal:50051

CMD ["./client"]
