# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swim.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'swim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nswim.proto\x12\x04swim\" \n\x0bPingRequest\x12\x11\n\tsender_id\x18\x01 \x01(\x05\"!\n\x0cPingResponse\x12\x11\n\tsender_id\x18\x01 \x01(\x05\";\n\x13IndirectPingRequest\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x11\n\ttarget_id\x18\x02 \x01(\x05\":\n\x14IndirectPingResponse\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x87\x01\n\x0bSwimService\x12/\n\x04Ping\x12\x11.swim.PingRequest\x1a\x12.swim.PingResponse\"\x00\x12G\n\x0cIndirectPing\x12\x19.swim.IndirectPingRequest\x1a\x1a.swim.IndirectPingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=20
  _globals['_PINGREQUEST']._serialized_end=52
  _globals['_PINGRESPONSE']._serialized_start=54
  _globals['_PINGRESPONSE']._serialized_end=87
  _globals['_INDIRECTPINGREQUEST']._serialized_start=89
  _globals['_INDIRECTPINGREQUEST']._serialized_end=148
  _globals['_INDIRECTPINGRESPONSE']._serialized_start=150
  _globals['_INDIRECTPINGRESPONSE']._serialized_end=208
  _globals['_SWIMSERVICE']._serialized_start=211
  _globals['_SWIMSERVICE']._serialized_end=346
# @@protoc_insertion_point(module_scope)
