FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN pip install grpcio grpcio-tools

# Generate Python code from proto file
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. two_phase_commit.proto

EXPOSE 50051

CMD ["python", "participant.py"]
