# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: two_phase_commit.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'two_phase_commit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16two_phase_commit.proto\x12\x10two_phase_commit\"%\n\x0bVoteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"L\n\x0cVoteResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12$\n\x04vote\x18\x02 \x01(\x0e\x32\x16.two_phase_commit.Vote*\x1d\n\x04Vote\x12\n\n\x06\x43OMMIT\x10\x00\x12\t\n\x05\x41\x42ORT\x10\x01\x32^\n\x0eTwoPhaseCommit\x12L\n\x0bRequestVote\x12\x1d.two_phase_commit.VoteRequest\x1a\x1e.two_phase_commit.VoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'two_phase_commit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTE']._serialized_start=161
  _globals['_VOTE']._serialized_end=190
  _globals['_VOTEREQUEST']._serialized_start=44
  _globals['_VOTEREQUEST']._serialized_end=81
  _globals['_VOTERESPONSE']._serialized_start=83
  _globals['_VOTERESPONSE']._serialized_end=159
  _globals['_TWOPHASECOMMIT']._serialized_start=192
  _globals['_TWOPHASECOMMIT']._serialized_end=286
# @@protoc_insertion_point(module_scope)
