// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/raft.proto

package raft

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogReplicator_ReplicateLog_FullMethodName = "/raft.LogReplicator/ReplicateLog"
)

// LogReplicatorClient is the client API for LogReplicator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogReplicatorClient interface {
	ReplicateLog(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
}

type logReplicatorClient struct {
	cc grpc.ClientConnInterface
}

func NewLogReplicatorClient(cc grpc.ClientConnInterface) LogReplicatorClient {
	return &logReplicatorClient{cc}
}

func (c *logReplicatorClient) ReplicateLog(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendEntriesResponse)
	err := c.cc.Invoke(ctx, LogReplicator_ReplicateLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogReplicatorServer is the server API for LogReplicator service.
// All implementations must embed UnimplementedLogReplicatorServer
// for forward compatibility.
type LogReplicatorServer interface {
	ReplicateLog(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	mustEmbedUnimplementedLogReplicatorServer()
}

// UnimplementedLogReplicatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogReplicatorServer struct{}

func (UnimplementedLogReplicatorServer) ReplicateLog(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicateLog not implemented")
}
func (UnimplementedLogReplicatorServer) mustEmbedUnimplementedLogReplicatorServer() {}
func (UnimplementedLogReplicatorServer) testEmbeddedByValue()                       {}

// UnsafeLogReplicatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogReplicatorServer will
// result in compilation errors.
type UnsafeLogReplicatorServer interface {
	mustEmbedUnimplementedLogReplicatorServer()
}

func RegisterLogReplicatorServer(s grpc.ServiceRegistrar, srv LogReplicatorServer) {
	// If the following call pancis, it indicates UnimplementedLogReplicatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogReplicator_ServiceDesc, srv)
}

func _LogReplicator_ReplicateLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogReplicatorServer).ReplicateLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogReplicator_ReplicateLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogReplicatorServer).ReplicateLog(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogReplicator_ServiceDesc is the grpc.ServiceDesc for LogReplicator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogReplicator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raft.LogReplicator",
	HandlerType: (*LogReplicatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReplicateLog",
			Handler:    _LogReplicator_ReplicateLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/raft.proto",
}
