# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swim.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'swim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nswim.proto\x12\x04swim\x1a\x1bgoogle/protobuf/empty.proto\" \n\x0bPingRequest\x12\x11\n\tsender_id\x18\x01 \x01(\x05\"!\n\x0cPingResponse\x12\x11\n\tsender_id\x18\x01 \x01(\x05\";\n\x13IndirectPingRequest\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x11\n\ttarget_id\x18\x02 \x01(\x05\":\n\x14IndirectPingResponse\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"<\n\x0bJoinRequest\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"7\n\x0cJoinResponse\x12\'\n\x0fmembership_list\x18\x01 \x03(\x0b\x32\x0e.swim.NodeInfo\"D\n\x17\x42roadcastFailureRequest\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x66\x61iled_node_id\x18\x02 \x01(\x05\"+\n\x18\x42roadcastFailureResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"7\n\x08NodeInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x32\xd1\x02\n\x0bSwimService\x12/\n\x04Ping\x12\x11.swim.PingRequest\x1a\x12.swim.PingResponse\"\x00\x12G\n\x0cIndirectPing\x12\x19.swim.IndirectPingRequest\x1a\x1a.swim.IndirectPingResponse\"\x00\x12/\n\x04Join\x12\x11.swim.JoinRequest\x1a\x12.swim.JoinResponse\"\x00\x12S\n\x10\x42roadcastFailure\x12\x1d.swim.BroadcastFailureRequest\x1a\x1e.swim.BroadcastFailureResponse\"\x00\x12\x42\n\x10StreamMembership\x12\x16.google.protobuf.Empty\x1a\x12.swim.JoinResponse\"\x00\x30\x01\x42\x08Z\x06./swimb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006./swim'
  _globals['_PINGREQUEST']._serialized_start=49
  _globals['_PINGREQUEST']._serialized_end=81
  _globals['_PINGRESPONSE']._serialized_start=83
  _globals['_PINGRESPONSE']._serialized_end=116
  _globals['_INDIRECTPINGREQUEST']._serialized_start=118
  _globals['_INDIRECTPINGREQUEST']._serialized_end=177
  _globals['_INDIRECTPINGRESPONSE']._serialized_start=179
  _globals['_INDIRECTPINGRESPONSE']._serialized_end=237
  _globals['_JOINREQUEST']._serialized_start=239
  _globals['_JOINREQUEST']._serialized_end=299
  _globals['_JOINRESPONSE']._serialized_start=301
  _globals['_JOINRESPONSE']._serialized_end=356
  _globals['_BROADCASTFAILUREREQUEST']._serialized_start=358
  _globals['_BROADCASTFAILUREREQUEST']._serialized_end=426
  _globals['_BROADCASTFAILURERESPONSE']._serialized_start=428
  _globals['_BROADCASTFAILURERESPONSE']._serialized_end=471
  _globals['_NODEINFO']._serialized_start=473
  _globals['_NODEINFO']._serialized_end=528
  _globals['_SWIMSERVICE']._serialized_start=531
  _globals['_SWIMSERVICE']._serialized_end=868
# @@protoc_insertion_point(module_scope)
