# Dockerfile.client
FROM python:3.9-slim

WORKDIR /app

# Install Python dependencies
RUN pip install grpcio grpcio-tools

# Copy all project files (including testclient.py, raft.proto, etc.)
COPY . .

# The default command is to run the testclient
CMD ["python", "-u", "testclient.py"]
