# Use the official Golang image as a base image
FROM golang:1.22

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod tidy

# Copy the rest of the application code into the container
COPY . .

# Build the Go server binary
RUN go build -o server .

# Expose port 50051 for gRPC communication
EXPOSE 50051

# Command to run the server when the container starts
CMD ["./server"]
