version: '3'

services:
  node1:
    build: .
    ports:
      - "50051:50051"
    environment:
      - NODE_ID=1

  node2:
    build: .
    ports:
      - "50052:50051"
    environment:
      - NODE_ID=2

  node3:
    build: .
    ports:
      - "50053:50051"
    environment:
      - NODE_ID=3

  node4:
    build: .
    ports:
      - "50054:50051"
    environment:
      - NODE_ID=4

  node5:
    build: .
    ports:
      - "50055:50051"
    environment:
      - NODE_ID=5
