[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0


[program:python_failure_detector]
command=python -u /app/src/main.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0        ; Disable log rotation
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:go_dissemination]
command=/app/dissemination-component
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0        ; Disable log rotation
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

