# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import two_phase_commit_pb2 as two__phase__commit__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in two_phase_commit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TwoPhaseCommitStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/two_phase_commit.TwoPhaseCommit/RequestVote',
                request_serializer=two__phase__commit__pb2.VoteRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.GlobalDecision = channel.unary_unary(
                '/two_phase_commit.TwoPhaseCommit/GlobalDecision',
                request_serializer=two__phase__commit__pb2.GlobalDecisionRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.GlobalDecisionResponse.FromString,
                _registered_method=True)
        self.SendVotes = channel.unary_unary(
                '/two_phase_commit.TwoPhaseCommit/SendVotes',
                request_serializer=two__phase__commit__pb2.VotesReport.SerializeToString,
                response_deserializer=two__phase__commit__pb2.AckResponse.FromString,
                _registered_method=True)


class TwoPhaseCommitServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendVotes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoPhaseCommitServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=two__phase__commit__pb2.VoteRequest.FromString,
                    response_serializer=two__phase__commit__pb2.VoteResponse.SerializeToString,
            ),
            'GlobalDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalDecision,
                    request_deserializer=two__phase__commit__pb2.GlobalDecisionRequest.FromString,
                    response_serializer=two__phase__commit__pb2.GlobalDecisionResponse.SerializeToString,
            ),
            'SendVotes': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVotes,
                    request_deserializer=two__phase__commit__pb2.VotesReport.FromString,
                    response_serializer=two__phase__commit__pb2.AckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'two_phase_commit.TwoPhaseCommit', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('two_phase_commit.TwoPhaseCommit', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoPhaseCommit(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/two_phase_commit.TwoPhaseCommit/RequestVote',
            two__phase__commit__pb2.VoteRequest.SerializeToString,
            two__phase__commit__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobalDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/two_phase_commit.TwoPhaseCommit/GlobalDecision',
            two__phase__commit__pb2.GlobalDecisionRequest.SerializeToString,
            two__phase__commit__pb2.GlobalDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendVotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/two_phase_commit.TwoPhaseCommit/SendVotes',
            two__phase__commit__pb2.VotesReport.SerializeToString,
            two__phase__commit__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
