# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: two_phase_commit.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'two_phase_commit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16two_phase_commit.proto\x12\x10two_phase_commit\"%\n\x0bVoteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"L\n\x0cVoteResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12$\n\x04vote\x18\x02 \x01(\x0e\x32\x16.two_phase_commit.Vote\"]\n\x15GlobalDecisionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12,\n\x08\x64\x65\x63ision\x18\x02 \x01(\x0e\x32\x1a.two_phase_commit.Decision\"T\n\x16GlobalDecisionResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\"\n\x03\x61\x63k\x18\x02 \x01(\x0e\x32\x15.two_phase_commit.Ack\"L\n\x0bVotesReport\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12%\n\x05votes\x18\x02 \x03(\x0e\x32\x16.two_phase_commit.Vote\"\x1f\n\x0b\x41\x63kResponse\x12\x10\n\x08received\x18\x01 \x01(\x08*\x1d\n\x04Vote\x12\n\n\x06\x43OMMIT\x10\x00\x12\t\n\x05\x41\x42ORT\x10\x01*/\n\x08\x44\x65\x63ision\x12\x11\n\rGLOBAL_COMMIT\x10\x00\x12\x10\n\x0cGLOBAL_ABORT\x10\x01*\x12\n\x03\x41\x63k\x12\x0b\n\x07SUCCESS\x10\x00\x32\x8e\x02\n\x0eTwoPhaseCommit\x12L\n\x0bRequestVote\x12\x1d.two_phase_commit.VoteRequest\x1a\x1e.two_phase_commit.VoteResponse\x12\x63\n\x0eGlobalDecision\x12\'.two_phase_commit.GlobalDecisionRequest\x1a(.two_phase_commit.GlobalDecisionResponse\x12I\n\tSendVotes\x12\x1d.two_phase_commit.VotesReport\x1a\x1d.two_phase_commit.AckResponseB\x1bZ\x19twopc_project/twopc_go_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'two_phase_commit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031twopc_project/twopc_go_pb'
  _globals['_VOTE']._serialized_start=453
  _globals['_VOTE']._serialized_end=482
  _globals['_DECISION']._serialized_start=484
  _globals['_DECISION']._serialized_end=531
  _globals['_ACK']._serialized_start=533
  _globals['_ACK']._serialized_end=551
  _globals['_VOTEREQUEST']._serialized_start=44
  _globals['_VOTEREQUEST']._serialized_end=81
  _globals['_VOTERESPONSE']._serialized_start=83
  _globals['_VOTERESPONSE']._serialized_end=159
  _globals['_GLOBALDECISIONREQUEST']._serialized_start=161
  _globals['_GLOBALDECISIONREQUEST']._serialized_end=254
  _globals['_GLOBALDECISIONRESPONSE']._serialized_start=256
  _globals['_GLOBALDECISIONRESPONSE']._serialized_end=340
  _globals['_VOTESREPORT']._serialized_start=342
  _globals['_VOTESREPORT']._serialized_end=418
  _globals['_ACKRESPONSE']._serialized_start=420
  _globals['_ACKRESPONSE']._serialized_end=451
  _globals['_TWOPHASECOMMIT']._serialized_start=554
  _globals['_TWOPHASECOMMIT']._serialized_end=824
# @@protoc_insertion_point(module_scope)
