services:
  node1:
    build: .
    container_name: node1
    command: ["python", "-u", "raft-election.py", "-id=1", "-port=5001", "-peers=node2:5002,node3:5003,node4:5004,node5:5005"]
    ports:
      - "5001:5001"
    networks:
      - raft-network

  node2:
    build: .
    container_name: node2
    command: ["python", "-u", "raft-election.py", "-id=2", "-port=5002", "-peers=node1:5001,node3:5003,node4:5004,node5:5005"]
    ports:
      - "5002:5002"
    networks:
      - raft-network

  node3:
    build: .
    container_name: node3
    command: ["python", "-u", "raft-election.py", "-id=3", "-port=5003", "-peers=node1:5001,node2:5002,node4:5004,node5:5005"]
    ports:
      - "5003:5003"
    networks:
      - raft-network

  node4:
    build: .
    container_name: node4
    command: ["python", "-u", "raft-election.py", "-id=4", "-port=5004", "-peers=node1:5001,node2:5002,node3:5003,node5:5005"]
    ports:
      - "5004:5004"
    networks:
      - raft-network

  node5:
    build: .
    container_name: node5
    command: ["python", "-u", "raft-election.py", "-id=5", "-port=5005", "-peers=node1:5001,node2:5002,node3:5003,node4:5004"]
    ports:
      - "5005:5005"
    networks:
      - raft-network

networks:
  raft-network:
    driver: bridge