// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: proto/average.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Calculator_Average_FullMethodName        = "/average.Calculator/Average"
	Calculator_RunningAverage_FullMethodName = "/average.Calculator/RunningAverage"
)

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorClient interface {
	Average(ctx context.Context, in *AverageRequest, opts ...grpc.CallOption) (*AverageResponse, error)
	RunningAverage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NumberRequest, AverageResponse], error)
}

type calculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorClient(cc grpc.ClientConnInterface) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Average(ctx context.Context, in *AverageRequest, opts ...grpc.CallOption) (*AverageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AverageResponse)
	err := c.cc.Invoke(ctx, Calculator_Average_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) RunningAverage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NumberRequest, AverageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Calculator_ServiceDesc.Streams[0], Calculator_RunningAverage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NumberRequest, AverageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Calculator_RunningAverageClient = grpc.ClientStreamingClient[NumberRequest, AverageResponse]

// CalculatorServer is the server API for Calculator service.
// All implementations must embed UnimplementedCalculatorServer
// for forward compatibility.
type CalculatorServer interface {
	Average(context.Context, *AverageRequest) (*AverageResponse, error)
	RunningAverage(grpc.ClientStreamingServer[NumberRequest, AverageResponse]) error
	mustEmbedUnimplementedCalculatorServer()
}

// UnimplementedCalculatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCalculatorServer struct{}

func (UnimplementedCalculatorServer) Average(context.Context, *AverageRequest) (*AverageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Average not implemented")
}
func (UnimplementedCalculatorServer) RunningAverage(grpc.ClientStreamingServer[NumberRequest, AverageResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RunningAverage not implemented")
}
func (UnimplementedCalculatorServer) mustEmbedUnimplementedCalculatorServer() {}
func (UnimplementedCalculatorServer) testEmbeddedByValue()                    {}

// UnsafeCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServer will
// result in compilation errors.
type UnsafeCalculatorServer interface {
	mustEmbedUnimplementedCalculatorServer()
}

func RegisterCalculatorServer(s grpc.ServiceRegistrar, srv CalculatorServer) {
	// If the following call pancis, it indicates UnimplementedCalculatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Calculator_ServiceDesc, srv)
}

func _Calculator_Average_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Average(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Calculator_Average_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Average(ctx, req.(*AverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_RunningAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServer).RunningAverage(&grpc.GenericServerStream[NumberRequest, AverageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Calculator_RunningAverageServer = grpc.ClientStreamingServer[NumberRequest, AverageResponse]

// Calculator_ServiceDesc is the grpc.ServiceDesc for Calculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "average.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Average",
			Handler:    _Calculator_Average_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunningAverage",
			Handler:       _Calculator_RunningAverage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/average.proto",
}
