// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: two_phase_commit.proto

package twopc_go_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TwoPhaseCommit_RequestVote_FullMethodName    = "/two_phase_commit.TwoPhaseCommit/RequestVote"
	TwoPhaseCommit_GlobalDecision_FullMethodName = "/two_phase_commit.TwoPhaseCommit/GlobalDecision"
	TwoPhaseCommit_SendVotes_FullMethodName      = "/two_phase_commit.TwoPhaseCommit/SendVotes"
)

// TwoPhaseCommitClient is the client API for TwoPhaseCommit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TwoPhaseCommitClient interface {
	RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
	GlobalDecision(ctx context.Context, in *GlobalDecisionRequest, opts ...grpc.CallOption) (*GlobalDecisionResponse, error)
	SendVotes(ctx context.Context, in *VotesReport, opts ...grpc.CallOption) (*AckResponse, error)
}

type twoPhaseCommitClient struct {
	cc grpc.ClientConnInterface
}

func NewTwoPhaseCommitClient(cc grpc.ClientConnInterface) TwoPhaseCommitClient {
	return &twoPhaseCommitClient{cc}
}

func (c *twoPhaseCommitClient) RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, TwoPhaseCommit_RequestVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twoPhaseCommitClient) GlobalDecision(ctx context.Context, in *GlobalDecisionRequest, opts ...grpc.CallOption) (*GlobalDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GlobalDecisionResponse)
	err := c.cc.Invoke(ctx, TwoPhaseCommit_GlobalDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twoPhaseCommitClient) SendVotes(ctx context.Context, in *VotesReport, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, TwoPhaseCommit_SendVotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwoPhaseCommitServer is the server API for TwoPhaseCommit service.
// All implementations must embed UnimplementedTwoPhaseCommitServer
// for forward compatibility.
type TwoPhaseCommitServer interface {
	RequestVote(context.Context, *VoteRequest) (*VoteResponse, error)
	GlobalDecision(context.Context, *GlobalDecisionRequest) (*GlobalDecisionResponse, error)
	SendVotes(context.Context, *VotesReport) (*AckResponse, error)
	mustEmbedUnimplementedTwoPhaseCommitServer()
}

// UnimplementedTwoPhaseCommitServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTwoPhaseCommitServer struct{}

func (UnimplementedTwoPhaseCommitServer) RequestVote(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedTwoPhaseCommitServer) GlobalDecision(context.Context, *GlobalDecisionRequest) (*GlobalDecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GlobalDecision not implemented")
}
func (UnimplementedTwoPhaseCommitServer) SendVotes(context.Context, *VotesReport) (*AckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVotes not implemented")
}
func (UnimplementedTwoPhaseCommitServer) mustEmbedUnimplementedTwoPhaseCommitServer() {}
func (UnimplementedTwoPhaseCommitServer) testEmbeddedByValue()                        {}

// UnsafeTwoPhaseCommitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TwoPhaseCommitServer will
// result in compilation errors.
type UnsafeTwoPhaseCommitServer interface {
	mustEmbedUnimplementedTwoPhaseCommitServer()
}

func RegisterTwoPhaseCommitServer(s grpc.ServiceRegistrar, srv TwoPhaseCommitServer) {
	// If the following call pancis, it indicates UnimplementedTwoPhaseCommitServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TwoPhaseCommit_ServiceDesc, srv)
}

func _TwoPhaseCommit_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwoPhaseCommitServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwoPhaseCommit_RequestVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwoPhaseCommitServer).RequestVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwoPhaseCommit_GlobalDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwoPhaseCommitServer).GlobalDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwoPhaseCommit_GlobalDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwoPhaseCommitServer).GlobalDecision(ctx, req.(*GlobalDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TwoPhaseCommit_SendVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VotesReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwoPhaseCommitServer).SendVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwoPhaseCommit_SendVotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwoPhaseCommitServer).SendVotes(ctx, req.(*VotesReport))
	}
	return interceptor(ctx, in, info, handler)
}

// TwoPhaseCommit_ServiceDesc is the grpc.ServiceDesc for TwoPhaseCommit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TwoPhaseCommit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "two_phase_commit.TwoPhaseCommit",
	HandlerType: (*TwoPhaseCommitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _TwoPhaseCommit_RequestVote_Handler,
		},
		{
			MethodName: "GlobalDecision",
			Handler:    _TwoPhaseCommit_GlobalDecision_Handler,
		},
		{
			MethodName: "SendVotes",
			Handler:    _TwoPhaseCommit_SendVotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "two_phase_commit.proto",
}
