# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: average.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'average.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raverage.proto\x12\x07\x61verage\",\n\x0e\x41verageRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"!\n\x0f\x41verageResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\"\x1f\n\rNumberRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\x32\x90\x01\n\nCalculator\x12<\n\x07\x41verage\x12\x17.average.AverageRequest\x1a\x18.average.AverageResponse\x12\x44\n\x0eRunningAverage\x12\x16.average.NumberRequest\x1a\x18.average.AverageResponse(\x01\x42*\n\x18io.grpc.examples.averageB\x0c\x41verageProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'average_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030io.grpc.examples.averageB\014AverageProtoP\001'
  _globals['_AVERAGEREQUEST']._serialized_start=26
  _globals['_AVERAGEREQUEST']._serialized_end=70
  _globals['_AVERAGERESPONSE']._serialized_start=72
  _globals['_AVERAGERESPONSE']._serialized_end=105
  _globals['_NUMBERREQUEST']._serialized_start=107
  _globals['_NUMBERREQUEST']._serialized_end=138
  _globals['_CALCULATOR']._serialized_start=141
  _globals['_CALCULATOR']._serialized_end=285
# @@protoc_insertion_point(module_scope)
